### ISSUE TITLE
测试问题-电话没有做限制

### ISSUE THREAD

**Issue by jia-sketch** [open-joinbase/JoinBase#17]
![1676020797121](https://user-images.githubusercontent.com/75467636/218053083-ad93a115-63fb-479f-91e6-87cca4d5af8e.jpg)

**Comment by joinbase0** [comment]
sorry, this is not related to the product. And this is also related to the document. The document is reference to all pages under the docs secondary link: https://joinbase.io/docs.
We will not fix the problem.
